### ISSUE TITLE
Col names treated as row in import.table.from.local_file_path module

### ISSUE THREAD

**Issue by MariellaCC** [DHARPA-Project/kiara_plugin.tabular#2]
The column names of a csv file seem to appear as a row instead of headers. See the example in the notebook https://github.com/DHARPA-Project/kiara_plugin.anom_processing/blob/develop/examples/jupyter/preprocessing_prep.ipynb in the part "1. CSV file onboarding" here with our example dataset "personnel.csv", more specifically the "table" output of the onboarding_result variable.

**Comment by makkus** [comment]
Should be fixed with latest version, there is an additonal input field to manually overwrite. I forgot to adapt the input field name in the `import.table.from.local_file_path` pipeline, so it's a bit unwieldy, that will be fixed in the next release, but didn't want to release a new version just for that. If there is no new release before the workshop(s), let me know and I'll do one anyway, so we have a nicer field name for then.
